export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const RESET_INGREDIENT = "RESET_INGREDIENT";

export const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";

export const ADD_BUN = "ADD_BUN";
export const SET_BUN = "SET_BUN";

export const SET_ORDER_NUMBER = "SET_ORDER_NUMBER";
export const REORDER_ITEMS = "REORDER_ITEMS";

export const SET_ORDER = "SET_ORDER";
export const RESET_ORDER = "RESET_ORDER";

export const SUBTRACT_BUN_AMOUNT = "SUBTRACT_BUN_AMOUNT";

export const INCREMENT_INGREDIENT = "INCREMENT_INGREDIENT";

export const ADD_BUN_PRICE = "ADD_BUN_PRICE";

export const ADD_INGREDIENT_PRICE = "ADD_INGREDIENT_PRICE";

export const SUBTRACT_INGREDIENT_AMOUNT = "SUBTRACT_INGREDIENT_AMOUNT";

export const SUBTRACT_INGREDIENT_PRICE = "SUBTRACT_INGREDIENT_PRICE";
